#.
#Migrate copycats to Create: Copycats+ when they receive a block update
migrateCopycatsOnBlockUpdate = true
#.
#Migrate copycats to Create: Copycats+ when their block entities are initialized
migrateCopycatsOnInitialize = true

#.
#Enable/disable features. Values on server override clients
[features]
	#.
	copycat_vertical_step = true
	six_way_gearbox = false
	encased_chain_cogwheel = false
	inverted_clutch = false
	empty_fan_catalyst = false
	parallel_gearbox = false
	freewheel_clutch = false
	shear_pin = false
	inverted_gearshift = false
	centrifugal_clutch = false
	copycat_slab = true
	overstress_clutch = false
	brake = false
	copycat_block = true
	copycat_beam = true
	brass_gearbox = false
	copycat_wall = true
	item_silo = true
	sequenced_pulse_generator = true
	copycat_fence_gate = true
	linked_transmitter = true
	copycat_stairs = true
	copycat_board = true
	copycat_fence = true

