# This config file is for getting default values, for use in propertymodifier-common.toml. It is NOT directly usable!
    [items.tools]
        # If not listed, the value for an item is 0.
        [items.tools.efficiency]
            "minecraft:wooden_shovel" = 3.5
            "minecraft:wooden_pickaxe" = 3.5
            "minecraft:wooden_axe" = 3.5
            "minecraft:wooden_hoe" = 3.5
            "minecraft:stone_shovel" = 5.0
            "minecraft:stone_pickaxe" = 5.0
            "minecraft:stone_axe" = 5.0
            "minecraft:stone_hoe" = 5.0
            "minecraft:golden_shovel" = 19.5
            "minecraft:golden_pickaxe" = 19.5
            "minecraft:golden_axe" = 19.5
            "minecraft:golden_hoe" = 19.5
            "minecraft:iron_shovel" = 6.5
            "minecraft:iron_pickaxe" = 6.5
            "minecraft:iron_axe" = 6.5
            "minecraft:iron_hoe" = 6.5
            "minecraft:diamond_shovel" = 8.0
            "minecraft:diamond_pickaxe" = 8.0
            "minecraft:diamond_axe" = 8.0
            "minecraft:diamond_hoe" = 8.0
            "minecraft:netherite_shovel" = 9.0
            "minecraft:netherite_pickaxe" = 9.0
            "minecraft:netherite_axe" = 9.0
            "minecraft:netherite_hoe" = 9.0
            "copperized:copper_pickaxe" = 5.0
            "copperized:copper_axe" = 5.0
            "copperized:copper_hoe" = 5.0
            "copperized:copper_shovel" = 5.0
            "alloyed:steel_pickaxe" = 6.0
            "alloyed:steel_axe" = 6.0
            "alloyed:steel_shovel" = 6.0
            "alloyed:steel_hoe" = 6.0
            "alloyed:steel_knife" = 6.0
            "farmersdelight:flint_knife" = 3.5
            "farmersdelight:iron_knife" = 6.5
            "farmersdelight:diamond_knife" = 8.0
            "farmersdelight:netherite_knife" = 9.0
            "farmersdelight:golden_knife" = 19.5
            "kubejs:rose_gold_rapier" = 12.0
            "kubejs:rose_gold_knife" = 12.0
            "kubejs:copper_knife" = 5.0
            "kubejs:bone_knife" = 3.5
            "kubejs:lead_pickaxe" = 4.75
            "kubejs:lead_shovel" = 4.75
            "kubejs:lead_hoe" = 4.75
            "kubejs:lead_axe" = 4.75
            "kubejs:lead_knife" = 4.75
            "caverns_and_chasms:silver_shovel" = 7.0
            "caverns_and_chasms:silver_pickaxe" = 7.0
            "caverns_and_chasms:silver_axe" = 7.0
            "caverns_and_chasms:silver_hoe" = 7.0
            "caverns_and_chasms:necromium_shovel" = 10.0
            "caverns_and_chasms:necromium_pickaxe" = 10.0
            "caverns_and_chasms:necromium_axe" = 10.0
            "caverns_and_chasms:necromium_hoe" = 10.0
            "miningmaster:haste_peridot_axe" = 9.0
            "miningmaster:power_pyrite_axe" = 9.0
            "miningmaster:kinetic_opal_axe" = 9.0
            "miningmaster:ultima_axe" = 10.5
            "miningmaster:haste_peridot_pickaxe" = 9.0
            "miningmaster:lucky_citrine_pickaxe" = 9.0
            "miningmaster:unbreaking_iolite_pickaxe" = 9.0
            "miningmaster:ultima_pickaxe" = 10.5
            "additionaladditions:rose_gold_axe" = 12.0
            "additionaladditions:rose_gold_pickaxe" = 12.0
            "additionaladditions:rose_gold_shovel" = 12.0
            "additionaladditions:rose_gold_hoe" = 12.0
            "additionaladditions:gilded_netherite_axe" = 10.0
            "additionaladditions:gilded_netherite_pickaxe" = 10.0
            "additionaladditions:gilded_netherite_shovel" = 10.0
            "additionaladditions:gilded_netherite_hoe" = 10.0
            "oreganized:bush_hammer" = 7.0
            "oreganized:electrum_shovel" = 18.0
            "oreganized:electrum_pickaxe" = 18.0
            "oreganized:electrum_axe" = 18.0
            "oreganized:electrum_hoe" = 18.0
            "oreganized:electrum_knife" = 18.0
            "abnormals_delight:silver_knife" = 7.0
            "abnormals_delight:necromium_knife" = 10.0
        # If not listed, the value for an item is 0.
        [items.tools.attack_damage]
            "minecraft:wooden_sword" = 5.0
            "minecraft:wooden_shovel" = 3.5
            "minecraft:wooden_pickaxe" = 3.0
            "minecraft:wooden_axe" = 8.0
            "minecraft:wooden_hoe" = 2.0
            "minecraft:stone_sword" = 6.0
            "minecraft:stone_shovel" = 4.5
            "minecraft:stone_pickaxe" = 4.0
            "minecraft:stone_axe" = 10.0
            "minecraft:stone_hoe" = 2.0
            "minecraft:golden_sword" = 5.0
            "minecraft:golden_shovel" = 3.5
            "minecraft:golden_pickaxe" = 3.0
            "minecraft:golden_axe" = 8.0
            "minecraft:golden_hoe" = 2.0
            "minecraft:iron_sword" = 7.0
            "minecraft:iron_shovel" = 5.5
            "minecraft:iron_pickaxe" = 5.0
            "minecraft:iron_axe" = 10.0
            "minecraft:iron_hoe" = 2.0
            "minecraft:diamond_sword" = 8.0
            "minecraft:diamond_shovel" = 6.5
            "minecraft:diamond_pickaxe" = 6.0
            "minecraft:diamond_axe" = 10.0
            "minecraft:diamond_hoe" = 2.0
            "minecraft:netherite_sword" = 9.0
            "minecraft:netherite_shovel" = 7.5
            "minecraft:netherite_pickaxe" = 7.0
            "minecraft:netherite_axe" = 11.0
            "minecraft:netherite_hoe" = 2.0
            "minecraft:trident" = 10.0
            "mace_backport:mace" = 8.0
            "copperized:copper_sword" = 6.5
            "copperized:copper_pickaxe" = 4.5
            "copperized:copper_axe" = 10.0
            "copperized:copper_hoe" = 2.0
            "copperized:copper_shovel" = 5.0
            "alloyed:steel_sword" = 8.0
            "alloyed:steel_pickaxe" = 6.0
            "alloyed:steel_axe" = 10.0
            "alloyed:steel_shovel" = 6.5
            "alloyed:steel_hoe" = 2.0
            "alloyed:steel_knife" = 5.5
            "farmersdelight:flint_knife" = 3.5
            "farmersdelight:iron_knife" = 4.5
            "farmersdelight:diamond_knife" = 5.5
            "farmersdelight:netherite_knife" = 6.5
            "farmersdelight:golden_knife" = 2.5
            "kubejs:rose_gold_rapier" = 4.0
            "kubejs:rose_gold_knife" = 5.5
            "kubejs:copper_knife" = 4.0
            "kubejs:bone_knife" = 4.0
            "kubejs:lead_pickaxe" = 4.0
            "kubejs:lead_shovel" = 4.0
            "kubejs:lead_hoe" = 4.0
            "kubejs:lead_axe" = 4.0
            "kubejs:lead_sword" = 4.0
            "kubejs:lead_knife" = 4.0
            "caverns_and_chasms:silver_sword" = 3.0
            "caverns_and_chasms:silver_shovel" = 3.5
            "caverns_and_chasms:silver_pickaxe" = 3.0
            "caverns_and_chasms:silver_axe" = 6.0
            "caverns_and_chasms:silver_hoe" = 2.0
            "caverns_and_chasms:necromium_sword" = 8.0
            "caverns_and_chasms:necromium_shovel" = 6.5
            "caverns_and_chasms:necromium_pickaxe" = 6.0
            "caverns_and_chasms:necromium_axe" = 10.0
            "caverns_and_chasms:necromium_hoe" = 2.0
            "miningmaster:fire_ruby_sword" = 8.5
            "miningmaster:ice_sapphire_sword" = 8.5
            "miningmaster:spirit_garnet_sword" = 8.5
            "miningmaster:lucky_citrine_sword" = 8.5
            "miningmaster:power_pyrite_sword" = 8.5
            "miningmaster:ultima_sword" = 9.5
            "miningmaster:haste_peridot_axe" = 10.5
            "miningmaster:power_pyrite_axe" = 10.5
            "miningmaster:kinetic_opal_axe" = 10.5
            "miningmaster:ultima_axe" = 11.5
            "miningmaster:haste_peridot_pickaxe" = 6.5
            "miningmaster:lucky_citrine_pickaxe" = 6.5
            "miningmaster:unbreaking_iolite_pickaxe" = 6.5
            "miningmaster:ultima_pickaxe" = 7.5
            "additionaladditions:rose_gold_sword" = 8.0
            "additionaladditions:rose_gold_axe" = 10.0
            "additionaladditions:rose_gold_pickaxe" = 5.0
            "additionaladditions:rose_gold_shovel" = 5.5
            "additionaladditions:rose_gold_hoe" = 2.0
            "additionaladditions:gilded_netherite_sword" = 9.0
            "additionaladditions:gilded_netherite_axe" = 11.0
            "additionaladditions:gilded_netherite_pickaxe" = 7.0
            "additionaladditions:gilded_netherite_shovel" = 7.5
            "additionaladditions:gilded_netherite_hoe" = 2.0
            "oreganized:bush_hammer" = 6.0
            "oreganized:electrum_sword" = 8.0
            "oreganized:electrum_shovel" = 6.5
            "oreganized:electrum_pickaxe" = 6.0
            "oreganized:electrum_axe" = 11.0
            "oreganized:electrum_hoe" = 5.0
            "oreganized:electrum_knife" = 5.5
            "oreganized:electrum_machete" = 7.0
            "webasemod:wooden_bat" = 3.0
            "webasemod:stone_bat" = 4.0
            "webasemod:golden_bat" = 3.0
            "webasemod:iron_bat" = 5.0
            "webasemod:diamond_bat" = 6.0
            "webasemod:netherite_bat" = 7.0
            "nethersdelight:iron_machete" = 6.0
            "nethersdelight:diamond_machete" = 7.0
            "nethersdelight:netherite_machete" = 8.0
            "nethersdelight:golden_machete" = 4.0
            "abnormals_delight:silver_knife" = 2.5
            "abnormals_delight:necromium_knife" = 5.5
        # If not listed, the value for an item is 0.
        [items.tools.attack_speed]
            "minecraft:wooden_sword" = 1.5999999
            "minecraft:wooden_shovel" = 1.0
            "minecraft:wooden_pickaxe" = 1.2
            "minecraft:wooden_axe" = 0.79999995
            "minecraft:wooden_hoe" = 1.0
            "minecraft:stone_sword" = 1.5999999
            "minecraft:stone_shovel" = 1.0
            "minecraft:stone_pickaxe" = 1.2
            "minecraft:stone_axe" = 0.79999995
            "minecraft:stone_hoe" = 2.0
            "minecraft:golden_sword" = 1.5999999
            "minecraft:golden_shovel" = 1.0
            "minecraft:golden_pickaxe" = 1.2
            "minecraft:golden_axe" = 1.0
            "minecraft:golden_hoe" = 1.0
            "minecraft:iron_sword" = 1.5999999
            "minecraft:iron_shovel" = 1.0
            "minecraft:iron_pickaxe" = 1.2
            "minecraft:iron_axe" = 0.9000001
            "minecraft:iron_hoe" = 3.0
            "minecraft:diamond_sword" = 1.5999999
            "minecraft:diamond_shovel" = 1.0
            "minecraft:diamond_pickaxe" = 1.2
            "minecraft:diamond_axe" = 1.0
            "minecraft:diamond_hoe" = 4.0
            "minecraft:netherite_sword" = 1.5999999
            "minecraft:netherite_shovel" = 1.0
            "minecraft:netherite_pickaxe" = 1.2
            "minecraft:netherite_axe" = 1.0
            "minecraft:netherite_hoe" = 4.0
            "minecraft:trident" = 1.0999999
            "mace_backport:mace" = 1.5999999
            "copperized:copper_sword" = 1.5999999
            "copperized:copper_pickaxe" = 1.2
            "copperized:copper_axe" = 0.9000001
            "copperized:copper_hoe" = 3.0
            "copperized:copper_shovel" = 1.0
            "alloyed:steel_sword" = 1.5999999
            "alloyed:steel_pickaxe" = 1.2
            "alloyed:steel_axe" = 1.0
            "alloyed:steel_shovel" = 1.0
            "alloyed:steel_hoe" = 4.0
            "alloyed:steel_knife" = 2.0
            "farmersdelight:flint_knife" = 2.0
            "farmersdelight:iron_knife" = 2.0
            "farmersdelight:diamond_knife" = 2.0
            "farmersdelight:netherite_knife" = 2.0
            "farmersdelight:golden_knife" = 2.0
            "kubejs:rose_gold_rapier" = 4.0
            "kubejs:rose_gold_knife" = 2.0
            "kubejs:copper_knife" = 2.0
            "kubejs:bone_knife" = 2.0
            "kubejs:lead_pickaxe" = 2.0
            "kubejs:lead_shovel" = 2.0
            "kubejs:lead_hoe" = 2.0
            "kubejs:lead_axe" = 2.0
            "kubejs:lead_sword" = 2.0
            "kubejs:lead_knife" = 2.0
            "caverns_and_chasms:silver_sword" = 1.5999999
            "caverns_and_chasms:silver_shovel" = 1.0
            "caverns_and_chasms:silver_pickaxe" = 1.2
            "caverns_and_chasms:silver_axe" = 1.0
            "caverns_and_chasms:silver_hoe" = 1.0
            "caverns_and_chasms:necromium_sword" = 1.5999999
            "caverns_and_chasms:necromium_shovel" = 1.0
            "caverns_and_chasms:necromium_pickaxe" = 1.2
            "caverns_and_chasms:necromium_axe" = 1.0
            "caverns_and_chasms:necromium_hoe" = 4.0
            "miningmaster:fire_ruby_sword" = 1.5999999
            "miningmaster:ice_sapphire_sword" = 1.5999999
            "miningmaster:spirit_garnet_sword" = 1.5999999
            "miningmaster:lucky_citrine_sword" = 1.5999999
            "miningmaster:power_pyrite_sword" = 1.5999999
            "miningmaster:ultima_sword" = 1.5999999
            "miningmaster:haste_peridot_axe" = 1.0
            "miningmaster:power_pyrite_axe" = 1.0
            "miningmaster:kinetic_opal_axe" = 1.0
            "miningmaster:ultima_axe" = 1.0
            "miningmaster:haste_peridot_pickaxe" = 1.2
            "miningmaster:lucky_citrine_pickaxe" = 1.2
            "miningmaster:unbreaking_iolite_pickaxe" = 1.2
            "miningmaster:ultima_pickaxe" = 1.2
            "additionaladditions:rose_gold_sword" = 1.5999999
            "additionaladditions:rose_gold_axe" = 0.9000001
            "additionaladditions:rose_gold_pickaxe" = 1.2
            "additionaladditions:rose_gold_shovel" = 1.0
            "additionaladditions:rose_gold_hoe" = 3.0
            "additionaladditions:gilded_netherite_sword" = 1.5999999
            "additionaladditions:gilded_netherite_axe" = 1.0
            "additionaladditions:gilded_netherite_pickaxe" = 1.4000001
            "additionaladditions:gilded_netherite_shovel" = 1.0
            "additionaladditions:gilded_netherite_hoe" = 4.0
            "oreganized:bush_hammer" = 1.2
            "oreganized:electrum_sword" = 1.8
            "oreganized:electrum_shovel" = 1.2
            "oreganized:electrum_pickaxe" = 1.4000001
            "oreganized:electrum_axe" = 1.2
            "oreganized:electrum_hoe" = 1.2
            "oreganized:electrum_knife" = 2.2
            "oreganized:electrum_machete" = 1.5999999
            "webasemod:wooden_bat" = 1.2
            "webasemod:stone_bat" = 1.2
            "webasemod:golden_bat" = 1.2
            "webasemod:iron_bat" = 1.2
            "webasemod:diamond_bat" = 1.2
            "webasemod:netherite_bat" = 1.2
            "nethersdelight:iron_machete" = 1.4000001
            "nethersdelight:diamond_machete" = 1.4000001
            "nethersdelight:netherite_machete" = 1.4000001
            "nethersdelight:golden_machete" = 1.4000001
            "abnormals_delight:silver_knife" = 2.0
            "abnormals_delight:necromium_knife" = 2.0
# Due to internal reasons, stripping, flattening, tilling and entity modifiers cannot be extracted.
